---
# TODO: in /etc/apache2/mods-enabled/php5.conf need to replace "Order Deny,Allow" to "Require all granted"
# TODO: module mpm_itk not enabled
# TODO: while first provision, apache2 not restarted and listen 80 port, nginx start fails

# need to install before apache2-mpm-itk
- name: Install Apache2 MPM ITK
  apt:
    pkg: libapache2-mpm-itk
    state: latest
  tags: [ apache2 ]

- name: Install Apache2 and modules
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - apache2-mpm-itk
    - libapache2-mod-php5
  notify: Restart apache
  tags: [ apache2 ]

- name: remoteip config
  template:
    src: remoteip.conf.j2
    dest: /etc/apache2/mods-available/remoteip.conf
  tags: [ apache2 ]


- name: Enable apache2 modules
  file:
    src: "/etc/apache2/mods-available/{{ item }}"
    dest: "/etc/apache2/mods-enabled/{{ item }}"
    state: link
  with_items: apache_modules
  notify: Restart apache
  tags: [ apache2 ]

- name: Disable default apache site
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent
  notify: Restart apache
  tags: [ apache2 ]

- name: Disable default-ssl apache site
  file:
    path: "/etc/apache2/sites-enabled/default-ssl.conf"
    state: absent
  notify: Restart apache
  tags: [ apache2 ]

- name: Configure Apache
  template:
    src: apache2.conf.j2
    dest: /etc/apache2/apache2.conf
  notify: Restart apache
  tags: [ apache2 ]

- name: Configure Apache ports
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
  register: apache_configure_ports
  tags: [ apache2 ]

- name: Restart Apache if ports changed
  service: name=apache2 state=restarted
  when: apache_configure_ports|changed
  tags: [ apache2 ]
