---
# TODO: in /etc/apache2/mods-enabled/php5.conf need to replace "Order Deny,Allow" to "Require all granted"
# TODO: module mpm_itk not enabled

# need to install before apache2-mpm-itk
- name: Install Apache2 MPM ITK
  apt:
    pkg: libapache2-mpm-itk
    state: latest
  tags: [ apache-php, apache ]

- name: Install Apache2 and modules
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - apache2-mpm-itk
    - libapache2-mod-php5
  notify: Restart apache
  tags: [ apache-php, apache ]

- name: remoteip config
  template:
    src: remoteip.conf.j2
    dest: /etc/apache2/mods-available/remoteip.conf
  tags: [ apache-php, apache ]


- name: Enable apache2 modules
  file:
    src: "/etc/apache2/mods-available/{{ item }}"
    dest: "/etc/apache2/mods-enabled/{{ item }}"
    state: link
  with_items: apache_modules
  notify: Restart apache
  tags: [ apache-php, apache ]

- name: Disable default apache site
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent
  notify: Restart apache
  tags: [ apache-php, apache ]

- name: Disable default-ssl apache site
  file:
    path: "/etc/apache2/sites-enabled/default-ssl.conf"
    state: absent
  notify: Restart apache
  tags: [ apache-php, apache ]

- name: Configure Apache
  template:
    src: apache2.conf.j2
    dest: /etc/apache2/apache2.conf
  notify: Restart apache
  tags: [ apache-php, apache ]

- name: Configure Apache ports
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify: Restart apache
  tags: [ apache-php, apache ]
